---@class layout
---@field 1 number x
---@field 2 number y
---@field 3 string [optional] Slot Type: 'input', 'Liquid Input', 'Output', 'Liquid Output', 'Shop'
---@field 4 string[] [optional] if slot is Input type you can define input oids.