---@class recipe
---@field item string the item oid that this recipe will craft
---@field recipe ingredient[] the ingredients to use for this recipe
---@field total number @[Optional] the total amount of the item you get when crafted, defaults to 1