---@class weather
---@field active boolean whether weather is current "on" or not
---@field start_time number the time weather will start today, in ms
---@field end_time string the time weather will end today, in ms