name: Create Archive
on:
  push:
    paths:
      - '**.lua'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Get next version
        uses: reecetech/version-increment@2022.5.1
        id: version
        with:
          scheme: calver
          increment: patch

      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'apicoapi.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig *.md'

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ steps.version.outputs.version }}"
          artifacts: "apicoapi.zip"
          token: ${{ secrets.GITHUB_TOKEN }}